services:
  db:
    image: mongo
    ports:
      - 3000:27017
  api:
    build: ./
    ports:
      - 3001:3001
    depends_on:
      - db
    environment:
      API_PORT: 3001
      DB_URL: mongodb://db:27017/RocketEngineApi
